### PR TITLE
Updated fio distributed client.yaml template to use run_snafu

### PR DESCRIPTION
**Pull request by acalhounRH**
Updated fio template file to execute run_snafu.py instead of fio_wrapper.py, Need to make this change to be compatible with snafu PR#38 

https://github.com/cloud-bulldozer/snafu/pull/38

### CODE REVIEW

**Comment by aakarshg** [comment]
ok to test

**Comment by acalhounRH** [comment]
Manually tested, everything checks out.

**Comment by aakarshg** [comment]
closing this as it's covered by #221

**Pull request closed without merging**
