### PR TITLE
Repo restructure

### PR DESCRIPTION
**Pull request by dustinblack**
Here is a first stab at the restructure for Issue #84.

I'm sure this will spark debate and require some tweaks as more eyes get on it, so I'm leaving my commits unsquashed for my own sanity for now.

### CODE REVIEW

**Comment by aakarshg** [comment]
can you please squash commits?

**Comment by dustinblack** [comment]
> can you please squash commits?

First lambast my changes and tell me I shouldn't move the CI stuff from `tests/` to `CI/` and that you've seen better work from middle-schooler. Then I'll cry into my beer for a while, make changes to resolve my utter shame, make sure the final version brings you the utmost joy, and then I'll rebase, squash, and ask nicely for you to merge.

**Comment by aakarshg** [comment]
Proposing to close this for the following 2 reasons:
1. state of this pr is an absolute mess
2. The repository structure should mirror that of how it'll be when using operator-sdk, as that would help us stay as close to framework as possible and not get into issues such as changes required in PR #112 which also triggered cascading changes to csvs in operatorhub with [PRs](https://github.com/operator-framework/community-operators/pull/607/files). We should also look at using `olm-catalog gen-csv --csv-version` to create csvs and just stick to the defaults, as i dont think any of us have cycles to keep in touch with operator-framework updates and this will reduce the burden.

**Comment by dustinblack** [comment]
@aakarshg This PR isn't in any usable state anymore, so I will close it. However, I still think that changes relevant to issue #84 are important.

**Pull request closed without merging**
