### PR TITLE
Better defaults and user modification of defaults through CR

### PR DESCRIPTION
**Pull request by dustinblack**
For issue #37 

Adding couchbase deployment

make operator and pod versions and urls variables changeable by CR

move default vars to defaults dir

making operator and pod versions and URLs user-configurable

### CODE REVIEW

**Comment by dustinblack** [comment]
rerun smoke

**Comment by aakarshg** [comment]
Seems to be failing on my 3.11 minishift environment at creating clusterrolebinding for the cb-operator :/ despite the other clusterrole, clusterrolebinding being applied successfully.

**Comment by dustinblack** [comment]
> Please apply rebase and also update the docs reflecting the new changes.

Updates done, and tests passed locally on minishift.

**Comment by dustinblack** [comment]
> Looks good for most part, we just need to edit the templates to make use of benchmark namespace instead of defaulting to current namespace. Another way we can do this, for now we can merge this if I'm able to get it to work locally and then make changes in #50

We currently use meta.namespace across other workloads, and the existing CI system (minishift, at least) would run tests within the benchmark namespace context already. I don't like the idea of hard-coding the benchmark namespace all over the place; I already don't like how much of this is in the deploy/ directory files.

**Comment by dustinblack** [comment]
Test passed for me on local minikube (after dealing with lab-related network annoyances)

**Comment by aakarshg** [comment]
Test passed on minishift if all other images were cleared from cache and rerun thrice. Will merge this as discussion related to namespace can take place at #54 .

**Pull request merged**
