### PR TITLE
Change reference to container images to SHA based reference for disco…

### PR DESCRIPTION
**Pull request by jeanchlopez**
…nnected environment compatibility

Let me know if this is the correct way to proceed

### CODE REVIEW

**Comment by dry923** [comment]
@jeanchlopez you can currently reference an image by sha using the workload image option that was added recently. Take a read of this https://github.com/cloud-bulldozer/ripsaw/blob/master/README.md#optional-workload-images

**Comment by aakarshg** [comment]
> @jeanchlopez you can currently reference an image by sha using the workload image option that was added recently. Take a read of this https://github.com/cloud-bulldozer/ripsaw/blob/master/README.md#optional-workload-images

+1 to what @dry923 has suggested here. pinning images to sha doesn't scale well, as everytime a new patch makes it through we'll have to update sha. As @dry923 suggested you can reference image by sha using workload image option, for the operator image.. I've a PR in progress with operatorhub to use shas - https://github.com/operator-framework/community-operators/pull/1690.

**Comment by jeanchlopez** [comment]
Will take a look and see it that can work.

**Comment by dry923** [comment]
As this PR would require a lot of regular maintenance to update the sha every time an image is updated and there is already a feature that allows the user to achieve this functionality I will be closing this request.

**Pull request closed without merging**
