### PR TITLE
Show benchmark type

### PR DESCRIPTION
**Pull request by rsevilla87**
Show benchmark type when getting Benchmark CRs from kubectl

### CODE REVIEW

**Comment by chawlanikhil24** [comment]
@rsevilla87 where it is suppose to show the additional information  ?
I can see that your code is active in the crd of ripsaw:

```bash
[root@openshift-master ripsaw]# oc describe crd benchmarks.ripsaw.cloudbulldozer.io
Name:         benchmarks.ripsaw.cloudbulldozer.io
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2019-07-05T06:27:46Z
  Generation:          1
  Resource Version:    403886
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/benchmarks.ripsaw.cloudbulldozer.io
  UID:                 008c16be-9eee-11e9-809a-0229defcd2e1
Spec:
  Additional Printer Columns:
    JSON Path:    .spec.workload.name
    Description:  The type of test to perform
    Name:         Type
    Type:         string
    JSON Path:    .metadata.creationTimestamp
    Name:         Age
    Type:         date
  Group:          ripsaw.cloudbulldozer.io
  Names:
    Kind:       Benchmark
    List Kind:  BenchmarkList
    Plural:     benchmarks
    Singular:   benchmark
  Scope:        Namespaced
  Subresources:
    Status:
  Version:  v1alpha1
  Versions:
    Name:     v1alpha1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Kind:       Benchmark
    List Kind:  BenchmarkList
    Plural:     benchmarks
    Singular:   benchmark
  Conditions:
    Last Transition Time:  2019-07-05T06:27:46Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1alpha1
Events:  <none>
```

**Comment by chawlanikhil24** [comment]
@rsevilla87 I got the column in `oc get benchmark` 

before:
```bash
[root@openshift-master ripsaw]# oc get benchmark
NAME                AGE
example-benchmark   22s
``` 
After:
```bash
[root@openshift-master ripsaw]# oc get benchmark
NAME                TYPE      AGE
example-benchmark   fio       13s
```

The change looks good to me.

**Comment by rsevilla87** [comment]
Yeah @chawlanikhil24 , you're right :) . Apologies for the poor explanation in the PR

**Pull request merged**
