### PR TITLE
Add pod anti-affinity rules to IO jobs

### PR DESCRIPTION
**Pull request by rsevilla87**
Ensure IO clients spread among different nodes

### CODE REVIEW

**Comment by bengland2** [comment]
@rsevilla87  why is this necessary?  It may well be a good idea but wouldn't the benchmark run without anti-affinity?

**Comment by aakarshg** [comment]
> @rsevilla87 why is this necessary? It may well be a good idea but wouldn't the benchmark run without anti-affinity?

That's interesting opinion too, if we can make it optional that'll be great so folks can either use it if they want or not use it as well.

**Comment by rsevilla87** [comment]
So you're proposing to execute jobs with anti-affinity in a configurable way. I can't see the use case where one use wants to run several IO clients from the same node. Possibly I'm missing something here.

pd: FIO servers already run with pod anti-affinity

**Comment by rsevilla87** [comment]
> if this is going to spread workload generator pods more evenly across physical hosts, then I'm all for it.

Indeed. This is the goal of this PR :)

**Comment by aakarshg** [comment]
> So you're proposing to execute jobs with anti-affinity in a configurable way. I can't see the use case where one use wants to run several IO clients from the same node. Possibly I'm missing something here.
> 
> pd: FIO servers already run with pod anti-affinity

Its not the same node, rather same sets of node.. so for example during our scale test, we only wanted the pods to land on worker nodes ( not infra/master/workload) so in that case we had to rebuild the image essentially, but maybe that's out of the scope of this PR as I mentioned earlier. 

For now, if we can just add a small README update about how we use antipodaffinity to spread the pods that'll be great :) I'll open an issue for the nodeselector label work.

**Comment by rsevilla87** [comment]
Exactly, nodeSelector is a different thing here. The scope of this PR is to evenly spread all workload pods across all nodes matched with the nodeSelector (which is currently static as you mentioned). I'll  add another commit to this PR to update the docs explaining this behavior.

**Comment by bengland2** [comment]
@rsevilla87 @dry923  it's hammer time - all of them passed except hammerdb

**Pull request merged**
