### PR TITLE
Add infra role for Kafka

### PR DESCRIPTION
**Pull request by dustinblack**
Includes deployment via strimzi operator using community operatorhub.io. Introduces an extras sub-role for fundamental tasks that may be reused in setting up operatorhub.io for other infra roles.

### CODE REVIEW

**Comment by jtaleric** [comment]
Should we rebase, or simply start over?

**Comment by jtaleric** [comment]
@dustinblack Should we rebase this, or simply close this PR and re-open with a new PR?

**Comment by dustinblack** [comment]
I can work on rebasing it, but I'd rather do it after merging PR #83.

**Comment by jtaleric** [comment]
@dustinblack maybe @dry923 can help out here. Test his Gitfu.

**Comment by dustinblack** [comment]
> @dustinblack maybe @dry923 can help out here. Test his Gitfu.

Yeah, it would be a good place to jump in and get some experience. I'm sure it needs a rebase and some reworking.

**Comment by dry923** [comment]
@dustinblack rebased your branch and updated it accordingly - https://github.com/dustinblack/ripsaw/pull/6

**Comment by dry923** [comment]
CI shows the new kafka code passed and ycsb failed.

**Comment by aakarshg** [comment]
closing this re: #121 and this made its way into https://github.com/cloud-bulldozer/cloud-builder

**Pull request closed without merging**
