### PR TITLE
Fio-distributed running multiple samples

### PR DESCRIPTION
**Pull request by aakarshg**
runnning/indexing with 2 samples - http://marquez.perf.lab.eng.rdu2.redhat.com:5601/goto/855d7859a84278374ed87c5cbe124076

### CODE REVIEW

**Comment by chawlanikhil24** [comment]
@aakarshg samples parameter is added only in docs, and test_crs, I think , its good to add the parameter in [crd]( resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml)  and set the default value to 1, like the way we do for clients.

**Comment by aakarshg** [comment]
nice catch @chawlanikhil24 , updated the crd.

**Pull request merged**
