### PR TITLE
switch smallfile to using run_snafu.py

### PR DESCRIPTION
**Pull request by bengland2**
Do not merge or test before snafu PR 50 is merged!
Using this branch I ran a 3-sample multi-operation smallfile test in AWS Ceph cluster.
take out loop for different operations
make operation list a CSV list for run_snafu.py smallfile_wrapper
no smallfile-master dir anymore

### CODE REVIEW

**Comment by bengland2** [comment]
I left out the ES env vars in the workload.yml.j2, putting that in.   Seems like this should be common code across benchmarks somehow.

**Comment by bengland2** [comment]
I think it's ready for merge now.  With this CR:
```
[bengland@bene-laptop ripsaw]$ more ../s.yaml 
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: example-benchmark
  namespace: my-ripsaw
spec:
  test_user: bene
  clustername: aws-2009-09-10
  es_server: ec2-18-220-65-133.us-east-2.compute.amazonaws.com
  es_port: 19020
  es_index: ripsaw-smallfile
...
```
I see these environment variables passed to run_snafu.py:
```
[bengland@bene-laptop ripsaw]$ oc describe pod smallfile-client-1-benchmark-fb23a1d7-vcwsr | more
Name:               smallfile-client-1-benchmark-fb23a1d7-vcwsr
...
    Environment:
      uuid:         fb23a1d7-6033-5745-92f8-d68a3b28a6e4
      test_user:    bene
      clustername:  aws-2009-09-10
      es:           ec2-18-220-65-133.us-east-2.compute.amazonaws.com
      es_port:      19020
      es_index:     ripsaw-smallfile
...
```
I also updated the reference CR in resources/crds/ so that people would know how to use elastic search with the benchmark.

I plan to test this with a real OCP cluster as soon as I can get my hands on one, but it loaded ES correctly when I ran it from a container in a CI mode so I don't expect a problem.

**Comment by bengland2** [comment]
do not merge yet, some strange behavior in tests/test_smallfile.sh where it's passing when it should fail.  Am running it in minishift now.   Will commit changes to the test script.

**Comment by bengland2** [comment]
ran tests/test_smallfile.sh successfully on minikube on my laptop.

**Comment by bengland2** [comment]
to be clear, I think this is ready for merge, the problem was that I was assuming certain environment 
 variables and the "samples" parameter would be provided in the CR that run_snafu.py consumes, but tests/test_crs/valid_smallfile.yaml does not provide them.    Since ripsaw is supposed to not require ES or multiple samples, I fixed it so it handles the case where they are not in CR.  Now the kube CI passes.

**Comment by bengland2** [comment]
smallfile passed on all 3 CI types

**Comment by bengland2** [comment]
Since there are now conflicts anyway, will re-examine to ensure that the status code from running smallfile is reflected in the status code returned by the shell script.

**Comment by bengland2** [comment]
So if I run bash tests/test_smallfile.sh on minishift with cloud-bulldozer/smallfile:master, it fails, without *any* logging of what went wrong.   but if I run it with the version I built, which should be consistent with snafu PR 50, then it succeeds, but "oc logs" does not report output from the beginning of the run!  It appears that what's in cloud-bulldozer has changed recently, and I suspect it reverted something that was in snafu PR 50.     Specifically I see [nothing in /usr/local/bin/](http://pastebin.test.redhat.com/802267)  for softlinks, which ripsaw smallfile now depends on.   

 latest change you did to smallfile causes a merge conflict, am working on resolving that.    IMO This is a consequence of having snafu be a separate repo from ripsaw - hard to synchronize changes across repos.

**Comment by bengland2** [comment]
I don't have write privs to resolve these conflicts, but I want you to take my version not the master branch version.    @aakarsh can you force that?  Since it passes minikube and kni, this is the last remaining issue here, am I right?  @acalhounRH FYI...

**Comment by aakarshg** [comment]
@bengland2 the issue seems to be around https://github.com/cloud-bulldozer/ripsaw/commit/64f4acd1cf9ed167505706a4890f0521c434b095.

**Comment by aakarshg** [comment]
@bengland2 i'll just wait for CI once more and if it looks good, will go ahead and merge after you give the green light with the way i merged :)

**Pull request merged**
