### PR TITLE
[Do not merge] Backpack test

### PR DESCRIPTION
**Pull request by rsevilla87**
Tests a backpack image built from https://github.com/cloud-bulldozer/backpack/pull/11 and https://github.com/cloud-bulldozer/bohica/pull/16

### CODE REVIEW

**Comment by dry923** [comment]
> /rerun all
@rsevilla87 btw if you want to just test backpack run /rerun all tests/test_backpack.sh

**Comment by dry923** [comment]
@rsevilla87 I re-ran the backpack test and it dumps a slew of errors starting with
```
dnf_packages is not part of our scribe module                           collection!
dnf_repos is not part of our scribe module                           collection!
```
and then 
```
1134 documents successfully indexed
484 documents couldn't be indexed
```
lastly an exceptionally long error thats really un-paste-able here but heres the head of it. I saved the log to backpack_log on the ci box
```
Indexing exception found ('484 document(s) failed to index.', [{'index': {'_index': 'k8s_configmaps-metadata', '_type': '_doc', '_id': 'tz5_tXMBorHmjmbLDXwt', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [value.data] of type [text] in document with id 'tz5_tXMBorHmjmbLDXwt'", 'caused_by': {'type': 'illegal_state_exception', 'reason': "Can't get text on a START_OBJECT at 1:323"}}, 'data': {'uuid': 'e56c6d7a-ef79-50d3-846f-63d6687d873e', 'timestamp': 1596477862, 'node_name': 'ip-10-0-167-34.us-west-2.compute.internal', 'pod_name': 'backpack-e56c6d7a-fh5n8', 'module': 'k8s_configmaps',
```

**Comment by rsevilla87** [comment]
> @rsevilla87 I re-ran the backpack test and it dumps a slew of errors starting with
> 
> ```
> dnf_packages is not part of our scribe module                           collection!
> dnf_repos is not part of our scribe module                           collection!
> ```
> 
> and then
> 
> ```
> 1134 documents successfully indexed
> 484 documents couldn't be indexed
> ```
> 
> lastly an exceptionally long error thats really un-paste-able here but heres the head of it. I saved the log to backpack_log on the ci box
> 
> ```
> Indexing exception found ('484 document(s) failed to index.', [{'index': {'_index': 'k8s_configmaps-metadata', '_type': '_doc', '_id': 'tz5_tXMBorHmjmbLDXwt', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [value.data] of type [text] in document with id 'tz5_tXMBorHmjmbLDXwt'", 'caused_by': {'type': 'illegal_state_exception', 'reason': "Can't get text on a START_OBJECT at 1:323"}}, 'data': {'uuid': 'e56c6d7a-ef79-50d3-846f-63d6687d873e', 'timestamp': 1596477862, 'node_name': 'ip-10-0-167-34.us-west-2.compute.internal', 'pod_name': 'backpack-e56c6d7a-fh5n8', 'module': 'k8s_configmaps',
> ```

20:22:09 + python3 tests/check_es.py -s search-cloud-perf-lqrf3jjtaqo7727m7ynd2xyt4y.us-west-2.es.amazonaws.com -p 80 -u e56c6d7a-ef79-50d3-846f-63d6687d873e -i k8s_namespaces-metadata
20:22:09 No result found in ES

**Comment by rsevilla87** [comment]
@dry923, after deleting the old problematic indices (They had incorrect mappings due to some tests I did) seems to be working fine now.

**Pull request closed without merging**
