### PR TITLE
Adding additional namespace specifics

### PR DESCRIPTION
**Pull request by mike10010100**
This allows each of these commands to be run and not error out.

### CODE REVIEW

**Comment by aakarshg** [comment]
Thanks for the submission @mike10010100 . The scripts in tests/ directory are for CI, and when we setup CI, we switch context to ripsaw so thus this won't be necessary at all.

**Comment by mike10010100** [comment]
Ah, I see. Fair enough. It was more that 90% of the scripts have this explicit `--namespace ripsaw` specification, but these did not. It also allows people to run all of the tests locally on their machines.

**Comment by aakarshg** [comment]
Ah I see what you mean, that's a fair point. I've just went over the other scripts and you're right, the others have the `--namespace` but these don't. I'll go ahead and merge the PR. Thanks again for the contribution.

**Comment by mike10010100** [comment]
Thank you! Love the project!

**Pull request merged**
